<!--
|	
|	Este archivo se incluye en /horario/index.php
|	
|	Contiene la tabla para elegir las horas en las que el alumno
|	está disponible.
|	
-->
<div class="well user-tabla-horario">
	<ol id="selectable">
		<li class="user-unselectable">Hora</li>
		<li class="user-unselectable">Lunes</li>
		<li class="user-unselectable">Martes</li>
		<li class="user-unselectable">Miércoles</li>
		<li class="user-unselectable">Jueves</li>
		<li class="user-unselectable">Viernes</li>
		<li class="user-unselectable">Sábado</li>
		<li class="user-unselectable">7:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">8:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">9:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">10:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">11:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">12:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">13:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">14:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">15:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">16:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">17:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">18:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">19:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="user-unselectable">20:00</li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
		<li class="ui-state-default"></li>
	</ol>
	<!-- For styling purposes -->
	<div style="clear:both;"></div>
</div>
